{{- $sa := .Values.serviceAccount -}}
{{- if and (kindIs "map" $sa) (default false $sa.create) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "flask-app.serviceAccountName" . }}
  labels:
    {{- include "flask-app.labels" . | nindent 4 }}
{{- end }}
