{{- $sa := .Values.serviceAccount -}}
{{- if and $sa $sa.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "flask-app.serviceAccountName" . }}
  labels:
    {{- include "flask-app.labels" . | nindent 4 }}
{{- end }}
